// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CozaStore_AspNetCore6.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240110140955_firstInit")]
    partial class firstInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.About", b =>
                {
                    b.Property<int>("AboutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutId"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OurMission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OurStory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AboutId");

                    b.ToTable("Abouts");

                    b.HasData(
                        new
                        {
                            AboutId = 1,
                            IsActive = true,
                            OurMission = "Mauris non lacinia magna. Sed nec lobortis dolor. Vestibulum rhoncus dignissim risus, sed consectetur erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam maximus mauris sit amet odio convallis, in pharetra magna gravida. Praesent sed nunc fermentum mi molestie tempor. Morbi vitae viverra odio. Pellentesque ac velit egestas, luctus arcu non, laoreet mauris. Sed in ipsum tempor, consequat odio in, porttitor ante. Ut mauris ligula, volutpat in sodales in, porta non odio. Pellentesque tempor urna vitae mi vestibulum, nec venenatis nulla lobortis. Proin at gravida ante. Mauris auctor purus at lacus maximus euismod. Pellentesque vulputate massa ut nisl hendrerit, eget elementum libero iaculis.\r\n\r\n> *Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn't really do it, they just saw something. It seemed obvious to them after a while.\r\n> \r\n> - Steve Job’s*",
                            OurStory = "**Lorem ipsum dolor sit amet**, consectetur adipiscing elit. Mauris consequat consequat enim, non auctor massa ultrices non. Morbi sed odio massa. Quisque at vehicula tellus, sed tincidunt augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas varius egestas diam, eu sodales metus scelerisque congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas gravida justo eu arcu egestas convallis. Nullam eu erat bibendum, tempus ipsum eget, dictum enim. Donec non neque ut enim dapibus tincidunt vitae nec augue. Suspendisse potenti. Proin ut est diam. Donec condimentum euismod tortor, eget facilisis diam faucibus et. Morbi a tempor elit.\r\n\r\nDonec gravida lorem elit, quis condimentum ex semper sit amet. Fusce eget ligula magna. Aliquam aliquam imperdiet sodales. Ut fringilla turpis in vehicula vehicula. Pellentesque congue ac orci ut gravida. Aliquam erat volutpat. Donec iaculis lectus a arcu facilisis, eu sodales lectus sagittis. Etiam pellentesque, magna vel dictum rutrum, neque justo eleifend elit, vel tincidunt erat arcu ut sem. Sed rutrum, turpis ut commodo efficitur, quam velit convallis ipsum, et maximus enim ligula ac ligula.\r\n\r\nAny questions? Let us know in store at 8th floor, 379 Hudson St, New York, NY 10018 or call us on *(+1) 96 716 6879*"
                        });
                });

            modelBuilder.Entity("Entities.Models.CartLine", b =>
                {
                    b.Property<int>("CartLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartLineID"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CartLineID");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartLine");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Men",
                            Slug = "men"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Women",
                            Slug = "women"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bag",
                            Slug = "bag"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Watch",
                            Slug = "watch"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hat",
                            Slug = "hat"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Glasses",
                            Slug = "glasses"
                        });
                });

            modelBuilder.Entity("Entities.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"), 1L, 1);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Entities.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"), 1L, 1);

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CouponDiscountPercentage")
                        .HasColumnType("float");

                    b.Property<int>("CouponStock")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Entities.Models.CustomUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Information", b =>
                {
                    b.Property<int>("InfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InfoId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InfoId");

                    b.ToTable("Informations");

                    b.HasData(
                        new
                        {
                            InfoId = 1,
                            Address = "123 Main St, Anytown, USA",
                            Email = "contact@example.com",
                            IsActive = true,
                            Phone = "(123) 456-7890"
                        });
                });

            modelBuilder.Entity("Entities.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CouponDiscount")
                        .HasColumnType("int");

                    b.Property<string>("CouponName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("GiftWrap")
                        .HasColumnType("bit");

                    b.Property<string>("Line1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Shipped")
                        .HasColumnType("bit");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubTotalQuantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Materials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo1Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo2Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo3Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Color = "Snow",
                            Description = "A modern and elegant black winter jacket. Long-sleeved, with a collar and belted waist.",
                            Dimensions = "Length: 70 cm, Chest: 100 cm, Sleeve: 60 cm",
                            IsActive = false,
                            Materials = "Wool Blend",
                            Name = "Elegant Winter Jacket",
                            Photo1Url = "/img/elegant-winter-jacket66.png",
                            Photo2Url = "/img/elegant-winter-jacket15.png",
                            Price = 500m,
                            SKU = "EWJ456",
                            Slug = "elegant-winter-jacket",
                            Weight = 800.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Color = "Multi-color",
                            Description = "A chic and contemporary ensemble, featuring luxurious textures and sophisticated styling.",
                            Dimensions = "Vary based on size",
                            IsActive = false,
                            Materials = "Mixed Fabrics",
                            Name = "Chic Contemporary Outfit",
                            Photo1Url = "/img/chic-contemporary-outfit56.png",
                            Photo2Url = "/img/chic-contemporary-outfit62.png",
                            Price = 350m,
                            SKU = "CCO789",
                            Slug = "chic-contemporary-outfit",
                            Weight = 500.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Color = "Beige and Pink",
                            Description = "A chic business casual outfit, perfect for a professional setting. Features a high-waisted skirt and a sophisticated blouse.",
                            Dimensions = "Vary based on size",
                            IsActive = false,
                            Materials = "Cotton Blend",
                            Name = "Business Casual Outfit",
                            Photo1Url = "/img/business-casual-outfit74.png",
                            Photo2Url = "/img/business-casual-outfit83.png",
                            Price = 450m,
                            SKU = "BCO1012",
                            Slug = "business-casual-outfit",
                            Weight = 550.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Color = "White and Blue",
                            Description = "A casual yet trendy outfit, featuring a fitted white t-shirt and stylish pants.",
                            Dimensions = "Vary based on size",
                            IsActive = false,
                            Materials = "Cotton and Elastane",
                            Name = "Trendy Casual Outfit",
                            Photo1Url = "/img/trendy-casual-outfit71.png",
                            Photo2Url = "/img/trendy-casual-outfit23.png",
                            Price = 200m,
                            SKU = "TCO1315",
                            Slug = "trendy-casual-outfit",
                            Weight = 300.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Color = "Black",
                            Description = "A sophisticated classic evening outfit, featuring a black off-the-shoulder dress.",
                            Dimensions = "Vary based on size",
                            IsActive = false,
                            Materials = "Satin",
                            Name = "Classic Evening Outfit",
                            Photo1Url = "/img/classic-evening-outfit11.png",
                            Photo2Url = "/img/classic-evening-outfit17.png",
                            Price = 450m,
                            SKU = "CEO1618",
                            Slug = "classic-evening-outfit",
                            Weight = 450.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Color = "Black",
                            Description = "Stylish eyeglasses with a classic, sophisticated design. Features a timeless frame suitable for any occasion.",
                            Dimensions = "Frame Width: 140 mm, Lens Height: 40 mm, Lens Width: 50 mm",
                            IsActive = false,
                            Materials = "Metal and Plastic",
                            Name = "Classic Eyeglasses",
                            Photo1Url = "/img/classic-eyeglasses47.png",
                            Price = 150m,
                            SKU = "CLSEG101",
                            Slug = "classic-eyeglasses",
                            Weight = 30.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 6,
                            Color = "Silver",
                            Description = "A pair of delicate, rimless eyeglasses, showcasing a modern and lightweight design.",
                            Dimensions = "Frame Width: 13.5 cm, Lens Height: 3.5 cm, Lens Width: 5 cm",
                            IsActive = false,
                            Materials = "Metal and Polycarbonate",
                            Name = "Fashionable Rimless Eyeglasses",
                            Photo1Url = "/img/fashionable-rimless-eyeglasses76.png",
                            Price = 350m,
                            SKU = "FRE102",
                            Slug = "fashionable-rimless-eyeglasses",
                            Weight = 25.0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 6,
                            Color = "Brown",
                            Description = "A pair of contemporary eyeglasses featuring a round frame with a stylish and modern design.",
                            Dimensions = "Frame Width: 14 cm, Lens Height: 4.2 cm, Lens Width: 4.5 cm",
                            IsActive = false,
                            Materials = "Acetate",
                            Name = "Contemporary Round Eyeglasses",
                            Photo1Url = "/img/contemporary-round-eyeglasses37.png",
                            Price = 320m,
                            SKU = "CRE103",
                            Slug = "contemporary-round-eyeglasses",
                            Weight = 28.0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Color = "Maroon (Fedora), Blue (Cap)",
                            Description = "This set features a sophisticated maroon fedora with a wide black band and a casual denim cap. The fedora offers an air of elegance, while the cap is perfect for everyday wear.",
                            Dimensions = "Fedora - One size fits all; Cap - Adjustable strap",
                            IsActive = false,
                            Materials = "Wool blend (Fedora), Denim (Cap)",
                            Name = "Sophisticated Fedora and Casual Cap",
                            Photo1Url = "/img/sophisticated-fedora-and-casual-cap92.png",
                            Price = 50m,
                            SKU = "HATCOMBO1920",
                            Slug = "sophisticated-fedora-and-casual-cap",
                            Weight = 2.5E+152
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Color = "Sand and Teal (Sun Hat), Teal (Beanie)",
                            Description = "A dual-season hat set featuring an elegant, wide-brimmed sun hat in a dual-tone of sand and teal, complete with a black ribbon, and a cozy knit beanie with a playful pompom.",
                            Dimensions = "Sun Hat - One size Beanie - Stretch fit",
                            IsActive = false,
                            Materials = "Straw (Sun Hat), Acrylic knit (Beanie)",
                            Name = "Elegant Wide-Brimmed Sun Hat and Knit Beanie",
                            Photo1Url = "/img/elegant-wide-brimmed-sun-hat-and-knit-beanie57.png",
                            Price = 60m,
                            SKU = "HATSET2122",
                            Slug = "elegant-wide-brimmed-sun-hat-and-knit-beanie",
                            Weight = 200.0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Color = "Silver Band",
                            Description = "This men's wristwatch features a sophisticated design with a silver stainless steel band and a striking dark blue dial. The watch includes a date function and is water-resistant.",
                            Dimensions = "Case Diameter - 40 mm, Band Width - 20 mm",
                            IsActive = false,
                            Materials = "Stainless Steel",
                            Name = "Men's Classic Blue Dial Watch",
                            Photo1Url = "/img/mens-classic-blue-dial-watch70.png",
                            Price = 250m,
                            SKU = "MCBDW3132",
                            Slug = "mens-classic-blue-dial-watch",
                            Weight = 120.0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Color = "Black",
                            Description = "A modern digital smartwatch with a sleek black rubber band and a large, rectangular digital display. It is designed for both men and women and comes with various smart features such as activity tracking and notifications.",
                            Dimensions = "Case Height - 44 mm, Case Width - 35 mm, Band Width - 22 mm",
                            IsActive = false,
                            Materials = "Rubber, Glass",
                            Name = "Unisex Digital Smartwatch",
                            Photo1Url = "/img/unisex-digital-smartwatch78.png",
                            Price = 300m,
                            SKU = "UDSW3334",
                            Slug = "unisex-digital-smartwatch",
                            Weight = 100.0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Color = "Black or Rose Gold",
                            Description = "This minimalist timepiece showcases a modern aesthetic with a simple yet elegant design. Suitable for all genders, it features a slim profile, a matte black or rose gold case, and a comfortable strap.",
                            Dimensions = "Case Diameter - 38 mm, Band Width - 18 mm",
                            IsActive = false,
                            Materials = "Metal, Leather",
                            Name = "Minimalist Unisex Timepiece",
                            Photo1Url = "/img/minimalist-unisex-timepiece64.png",
                            Price = 150m,
                            SKU = "MUTW3536",
                            Slug = "minimalist-unisex-timepiece",
                            Weight = 80.0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Color = "Dark Navy",
                            Description = "This suit features a contemporary design with a dark navy slim-fit blazer and matching trousers. The outfit is tailored to offer a sleek silhouette, perfect for business meetings or formal events.",
                            Dimensions = "Size varies by selection",
                            IsActive = false,
                            Materials = "Wool Blend",
                            Name = "Modern Slim-Fit Navy Suit",
                            Photo1Url = "/img/modern-slim-fit-navy-suit14.png",
                            Photo2Url = "/img/modern-slim-fit-navy-suit63.png",
                            Price = 350m,
                            SKU = "MSFNS3739",
                            Slug = "modern-slim-fit-navy-suit",
                            Weight = 1200.0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Color = "Light Grey",
                            Description = "A fashionable and relaxed outfit, perfect for casual outings. This set features a light grey, crew-neck sweater made from a soft, breathable knit, paired with dark denim jeans and complemented by classic white sneakers.",
                            Dimensions = "Size varies by selection",
                            IsActive = false,
                            Materials = "Cotton Knit (Sweater), Denim (Jeans), Leather (Sneakers)",
                            Name = "Trendy Casual Men's Outfit",
                            Photo1Url = "/img/trendy-casual-mens-outfit99.png",
                            Photo2Url = "/img/trendy-casual-mens-outfit8.png",
                            Price = 180m,
                            SKU = "TCMO4042",
                            Slug = "trendy-casual-mens-outfit",
                            Weight = 1000.0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Color = "Charcoal Grey",
                            Description = "A refined and versatile outfit suitable for various occasions. The ensemble includes a tailored charcoal grey wool blazer, a classic white dress shirt, dark navy dress trousers, and brown leather Oxford shoes.",
                            Dimensions = "Size varies by selection",
                            IsActive = false,
                            Materials = "Wool",
                            Name = "Smart Casual Men's Outfit",
                            Photo1Url = "/img/smart-casual-mens-outfit38.png",
                            Photo2Url = "/img/smart-casual-mens-outfit14.png",
                            Price = 350m,
                            SKU = "SCMO4344",
                            Slug = "smart-casual-mens-outfit",
                            Weight = 1500.0
                        });
                });

            modelBuilder.Entity("Entities.Models.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockId"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StockId");

                    b.HasIndex("ProductId");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            StockId = 1,
                            Color = "Snow",
                            ProductId = 1,
                            Quantity = 5,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 2,
                            Color = "Black",
                            ProductId = 2,
                            Quantity = 5,
                            Size = "S"
                        },
                        new
                        {
                            StockId = 3,
                            Color = "Pink",
                            ProductId = 3,
                            Quantity = 5,
                            Size = "M"
                        },
                        new
                        {
                            StockId = 4,
                            Color = "White",
                            ProductId = 4,
                            Quantity = 5,
                            Size = "XS"
                        },
                        new
                        {
                            StockId = 5,
                            Color = "Black",
                            ProductId = 5,
                            Quantity = 5,
                            Size = "L"
                        },
                        new
                        {
                            StockId = 6,
                            Color = "Black",
                            ProductId = 6,
                            Quantity = 20,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 7,
                            Color = "Silver",
                            ProductId = 7,
                            Quantity = 10,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 8,
                            Color = "Maroon (Fedora)",
                            ProductId = 8,
                            Quantity = 5,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 9,
                            Color = "Straw",
                            ProductId = 9,
                            Quantity = 5,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 10,
                            Color = "Silver Band",
                            ProductId = 10,
                            Quantity = 10,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 11,
                            Color = "Black",
                            ProductId = 11,
                            Quantity = 12,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 12,
                            Color = "Black",
                            ProductId = 12,
                            Quantity = 5,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 13,
                            Color = "Dark Navy",
                            ProductId = 13,
                            Quantity = 5,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 14,
                            Color = "Light Grey",
                            ProductId = 14,
                            Quantity = 5,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 15,
                            Color = "Charcoal Grey",
                            ProductId = 15,
                            Quantity = 5,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 16,
                            Color = "Blue",
                            ProductId = 1,
                            Quantity = 10,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 17,
                            Color = "Orange",
                            ProductId = 1,
                            Quantity = 10,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 18,
                            Color = "Orange",
                            ProductId = 1,
                            Quantity = 11,
                            Size = "L"
                        },
                        new
                        {
                            StockId = 19,
                            Color = "Blue",
                            ProductId = 1,
                            Quantity = 1,
                            Size = "L"
                        },
                        new
                        {
                            StockId = 20,
                            Color = "Purple",
                            ProductId = 1,
                            Quantity = 10,
                            Size = "M"
                        },
                        new
                        {
                            StockId = 21,
                            Color = "Red",
                            ProductId = 1,
                            Quantity = 15,
                            Size = "M"
                        },
                        new
                        {
                            StockId = 22,
                            Color = "Orange",
                            ProductId = 1,
                            Quantity = 6,
                            Size = "S"
                        },
                        new
                        {
                            StockId = 23,
                            Color = "Blue",
                            ProductId = 1,
                            Quantity = 12,
                            Size = "S"
                        },
                        new
                        {
                            StockId = 24,
                            Color = "Orange",
                            ProductId = 2,
                            Quantity = 1,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 25,
                            Color = "Orange",
                            ProductId = 2,
                            Quantity = 9,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 26,
                            Color = "Yellow",
                            ProductId = 2,
                            Quantity = 14,
                            Size = "L"
                        },
                        new
                        {
                            StockId = 27,
                            Color = "Green",
                            ProductId = 2,
                            Quantity = 8,
                            Size = "L"
                        },
                        new
                        {
                            StockId = 28,
                            Color = "Red",
                            ProductId = 2,
                            Quantity = 4,
                            Size = "M"
                        },
                        new
                        {
                            StockId = 29,
                            Color = "Purple",
                            ProductId = 2,
                            Quantity = 5,
                            Size = "M"
                        },
                        new
                        {
                            StockId = 30,
                            Color = "Purple",
                            ProductId = 2,
                            Quantity = 13,
                            Size = "S"
                        },
                        new
                        {
                            StockId = 31,
                            Color = "Purple",
                            ProductId = 2,
                            Quantity = 10,
                            Size = "S"
                        },
                        new
                        {
                            StockId = 32,
                            Color = "Yellow",
                            ProductId = 3,
                            Quantity = 4,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 33,
                            Color = "Red",
                            ProductId = 3,
                            Quantity = 4,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 34,
                            Color = "Blue",
                            ProductId = 3,
                            Quantity = 2,
                            Size = "L"
                        },
                        new
                        {
                            StockId = 35,
                            Color = "Purple",
                            ProductId = 3,
                            Quantity = 1,
                            Size = "L"
                        },
                        new
                        {
                            StockId = 36,
                            Color = "Red",
                            ProductId = 3,
                            Quantity = 8,
                            Size = "M"
                        },
                        new
                        {
                            StockId = 37,
                            Color = "Red",
                            ProductId = 3,
                            Quantity = 2,
                            Size = "M"
                        },
                        new
                        {
                            StockId = 38,
                            Color = "Blue",
                            ProductId = 3,
                            Quantity = 6,
                            Size = "S"
                        },
                        new
                        {
                            StockId = 39,
                            Color = "Green",
                            ProductId = 3,
                            Quantity = 5,
                            Size = "S"
                        },
                        new
                        {
                            StockId = 40,
                            Color = "Red",
                            ProductId = 4,
                            Quantity = 1,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 41,
                            Color = "Orange",
                            ProductId = 4,
                            Quantity = 9,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 42,
                            Color = "Orange",
                            ProductId = 4,
                            Quantity = 14,
                            Size = "L"
                        },
                        new
                        {
                            StockId = 43,
                            Color = "Orange",
                            ProductId = 4,
                            Quantity = 10,
                            Size = "L"
                        },
                        new
                        {
                            StockId = 44,
                            Color = "Purple",
                            ProductId = 4,
                            Quantity = 4,
                            Size = "M"
                        },
                        new
                        {
                            StockId = 45,
                            Color = "Purple",
                            ProductId = 4,
                            Quantity = 15,
                            Size = "M"
                        },
                        new
                        {
                            StockId = 46,
                            Color = "Green",
                            ProductId = 4,
                            Quantity = 2,
                            Size = "S"
                        },
                        new
                        {
                            StockId = 47,
                            Color = "Purple",
                            ProductId = 4,
                            Quantity = 15,
                            Size = "S"
                        },
                        new
                        {
                            StockId = 48,
                            Color = "Green",
                            ProductId = 5,
                            Quantity = 8,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 49,
                            Color = "Purple",
                            ProductId = 5,
                            Quantity = 14,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 50,
                            Color = "Red",
                            ProductId = 5,
                            Quantity = 7,
                            Size = "L"
                        },
                        new
                        {
                            StockId = 51,
                            Color = "Blue",
                            ProductId = 5,
                            Quantity = 11,
                            Size = "L"
                        },
                        new
                        {
                            StockId = 52,
                            Color = "Green",
                            ProductId = 5,
                            Quantity = 1,
                            Size = "M"
                        },
                        new
                        {
                            StockId = 53,
                            Color = "Yellow",
                            ProductId = 5,
                            Quantity = 4,
                            Size = "M"
                        },
                        new
                        {
                            StockId = 54,
                            Color = "Yellow",
                            ProductId = 5,
                            Quantity = 7,
                            Size = "S"
                        },
                        new
                        {
                            StockId = 55,
                            Color = "Purple",
                            ProductId = 5,
                            Quantity = 9,
                            Size = "S"
                        },
                        new
                        {
                            StockId = 56,
                            Color = "Yellow",
                            ProductId = 6,
                            Quantity = 3,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 57,
                            Color = "Purple",
                            ProductId = 6,
                            Quantity = 3,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 58,
                            Color = "Orange",
                            ProductId = 6,
                            Quantity = 7,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 59,
                            Color = "Green",
                            ProductId = 7,
                            Quantity = 7,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 60,
                            Color = "Green",
                            ProductId = 7,
                            Quantity = 7,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 61,
                            Color = "Blue",
                            ProductId = 7,
                            Quantity = 7,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 62,
                            Color = "Green",
                            ProductId = 8,
                            Quantity = 15,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 63,
                            Color = "Yellow",
                            ProductId = 8,
                            Quantity = 8,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 64,
                            Color = "Red",
                            ProductId = 8,
                            Quantity = 5,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 65,
                            Color = "Blue",
                            ProductId = 9,
                            Quantity = 5,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 66,
                            Color = "Red",
                            ProductId = 9,
                            Quantity = 14,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 67,
                            Color = "Yellow",
                            ProductId = 9,
                            Quantity = 8,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 68,
                            Color = "Orange",
                            ProductId = 10,
                            Quantity = 15,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 69,
                            Color = "Blue",
                            ProductId = 10,
                            Quantity = 2,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 70,
                            Color = "Yellow",
                            ProductId = 10,
                            Quantity = 14,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 71,
                            Color = "Yellow",
                            ProductId = 11,
                            Quantity = 14,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 72,
                            Color = "Red",
                            ProductId = 11,
                            Quantity = 8,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 73,
                            Color = "Green",
                            ProductId = 11,
                            Quantity = 6,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 74,
                            Color = "Blue",
                            ProductId = 12,
                            Quantity = 14,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 75,
                            Color = "Blue",
                            ProductId = 12,
                            Quantity = 11,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 76,
                            Color = "Orange",
                            ProductId = 12,
                            Quantity = 6,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 77,
                            Color = "Purple",
                            ProductId = 13,
                            Quantity = 3,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 78,
                            Color = "Green",
                            ProductId = 13,
                            Quantity = 9,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 79,
                            Color = "Red",
                            ProductId = 13,
                            Quantity = 1,
                            Size = "L"
                        },
                        new
                        {
                            StockId = 80,
                            Color = "Yellow",
                            ProductId = 13,
                            Quantity = 6,
                            Size = "L"
                        },
                        new
                        {
                            StockId = 81,
                            Color = "Green",
                            ProductId = 13,
                            Quantity = 3,
                            Size = "M"
                        },
                        new
                        {
                            StockId = 82,
                            Color = "Orange",
                            ProductId = 13,
                            Quantity = 3,
                            Size = "M"
                        },
                        new
                        {
                            StockId = 83,
                            Color = "Purple",
                            ProductId = 13,
                            Quantity = 1,
                            Size = "S"
                        },
                        new
                        {
                            StockId = 84,
                            Color = "Purple",
                            ProductId = 13,
                            Quantity = 12,
                            Size = "S"
                        },
                        new
                        {
                            StockId = 85,
                            Color = "Yellow",
                            ProductId = 14,
                            Quantity = 9,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 86,
                            Color = "Yellow",
                            ProductId = 14,
                            Quantity = 15,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 87,
                            Color = "Orange",
                            ProductId = 14,
                            Quantity = 6,
                            Size = "L"
                        },
                        new
                        {
                            StockId = 88,
                            Color = "Red",
                            ProductId = 14,
                            Quantity = 3,
                            Size = "L"
                        },
                        new
                        {
                            StockId = 89,
                            Color = "Purple",
                            ProductId = 14,
                            Quantity = 7,
                            Size = "M"
                        },
                        new
                        {
                            StockId = 90,
                            Color = "Yellow",
                            ProductId = 14,
                            Quantity = 4,
                            Size = "M"
                        },
                        new
                        {
                            StockId = 91,
                            Color = "Orange",
                            ProductId = 14,
                            Quantity = 12,
                            Size = "S"
                        },
                        new
                        {
                            StockId = 92,
                            Color = "Green",
                            ProductId = 14,
                            Quantity = 12,
                            Size = "S"
                        },
                        new
                        {
                            StockId = 93,
                            Color = "Green",
                            ProductId = 15,
                            Quantity = 14,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 94,
                            Color = "Orange",
                            ProductId = 15,
                            Quantity = 1,
                            Size = "XL"
                        },
                        new
                        {
                            StockId = 95,
                            Color = "Orange",
                            ProductId = 15,
                            Quantity = 1,
                            Size = "L"
                        },
                        new
                        {
                            StockId = 96,
                            Color = "Red",
                            ProductId = 15,
                            Quantity = 9,
                            Size = "L"
                        },
                        new
                        {
                            StockId = 97,
                            Color = "Purple",
                            ProductId = 15,
                            Quantity = 8,
                            Size = "M"
                        },
                        new
                        {
                            StockId = 98,
                            Color = "Green",
                            ProductId = 15,
                            Quantity = 14,
                            Size = "M"
                        },
                        new
                        {
                            StockId = 99,
                            Color = "Purple",
                            ProductId = 15,
                            Quantity = 8,
                            Size = "S"
                        },
                        new
                        {
                            StockId = 100,
                            Color = "Purple",
                            ProductId = 15,
                            Quantity = 14,
                            Size = "S"
                        },
                        new
                        {
                            StockId = 101,
                            Color = "Red",
                            ProductId = 16,
                            Quantity = 6,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 102,
                            Color = "Blue",
                            ProductId = 16,
                            Quantity = 1,
                            Size = "Fix"
                        },
                        new
                        {
                            StockId = 103,
                            Color = "Yellow",
                            ProductId = 16,
                            Quantity = 9,
                            Size = "Fix"
                        });
                });

            modelBuilder.Entity("Entities.Models.WishList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WishLists");
                });

            modelBuilder.Entity("Entities.Models.WishListProduct", b =>
                {
                    b.Property<int>("WishListProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishListProductId"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("WishListId")
                        .HasColumnType("int");

                    b.HasKey("WishListProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WishListId");

                    b.ToTable("WishListProducts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "50710b3c-51ee-4ec5-a3f4-320d6bc67d82",
                            ConcurrencyStamp = "622c9965-42f5-43a1-8210-1173150ba9f7",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "d4174acb-1ac5-4fb9-b617-03ee41baf0dd",
                            ConcurrencyStamp = "953fee96-131d-47dd-8a12-a6a6ab69eb1c",
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = "e2226d17-1ed0-4614-8830-774fbae66717",
                            ConcurrencyStamp = "083c3259-7916-4853-a1bc-028b44b5c013",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entities.Models.CartLine", b =>
                {
                    b.HasOne("Entities.Models.Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId");

                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Models.Order", b =>
                {
                    b.HasOne("Entities.Models.CustomUser", "CustomUser")
                        .WithMany("Orders")
                        .HasForeignKey("CustomUserId");

                    b.Navigation("CustomUser");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Models.Stock", b =>
                {
                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Models.WishList", b =>
                {
                    b.HasOne("Entities.Models.CustomUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.WishListProduct", b =>
                {
                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany("WishListProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.WishList", "WishList")
                        .WithMany("WishListProducts")
                        .HasForeignKey("WishListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("WishList");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Models.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Models.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Entities.Models.CustomUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Entities.Models.Order", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Navigation("Stocks");

                    b.Navigation("WishListProducts");
                });

            modelBuilder.Entity("Entities.Models.WishList", b =>
                {
                    b.Navigation("WishListProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
